### ISSUE TITLE
Python 3 not compatible?

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/brat_to_cdli_conll_converter#1]
epp@waga-masta:/alty/data/brat2conll$ brat2conll
Traceback (most recent call last):
  File "/usr/local/bin/brat2conll", line 11, in <module>
    load_entry_point('brat2conllconverter==0.0.0', 'console_scripts', 'brat2conll')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'brat_to_cdli_conll_converter'

**Comment by greek-geek** [comment]
I have fixed the code. It should work with Python3 now. Please check.
